version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

  app1:
    image: nginx:alpine
    volumes:
      - ./app1/index.html:/usr/share/nginx/html/index.html
      - ./app1/images:/usr/share/nginx/html/images
      - ./app1/css:/usr/share/nginx/html/css

  app2:
    image: nginx:alpine
    volumes:
      - ./app2/index.html:/usr/share/nginx/html/index.html
      - ./app2/images:/usr/share/nginx/html/images
      - ./app2/css:/usr/share/nginx/html/css
